import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sansFont = localFont({
  src: [
    {
      path: "../public/fonts/PPNeueMontreal-Medium.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${sansFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-body">{children}</body>
    </html>
  );
}
